---
title: notice_error (PythonエージェントAPI)
type: apiDoc
shortDescription: Pythonの例外の詳細をエラーとして記録します。
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: This call records the details of a Python exception as an error.'
translationType: machine
---

## 構文

```
newrelic.agent.notice_error(error=None, attributes={}, expected=None, ignore=None, status_code=None, application=None)
```

Pythonの例外の詳細をエラーとして記録します。

## 説明

デフォルトでは、Python エージェントは処理されない例外のみを報告します。 `notice_error` を使用すると、Python の例外をエラーとして記録し、New Relic One で確認することができます。パラメータが指定されていない場合は、現在処理されている例外の詳細が使用されます。

[トランザクションごとに最大5つの異なる例外を記録することができます。](/docs/accounts-partnerships/education/getting-started-new-relic/glossary#transaction) また、 [ハーベストサイクルごとにすべてのトランザクションの合計で最大20の例外を記録することができます。](/docs/apm/new-relic-apm/getting-started/glossary#harvest-cycle) 。

監視しているウェブリクエストやバックグラウンドタスクのコンテキスト内で `notice_error()` が呼び出されると、リクエストやタスクが報告されているアプリケーションに対して、例外の詳細が報告されます。

監視対象のウェブリクエストやバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`application`](/docs/agents/python-agent/python-agent-api/application) キーワード引数が提供され、例外を記録する必要のあるアプリケーションに対応するアプリケーションオブジェクトが提供されない限り、呼び出しは無視されます。適切なアプリケーション・オブジェクトは、 `newrelic.agent.application()` 関数を使って取得できます。

## パラメータ

<Callout variant="tip">
  ほとんどの場合、 `notice_error` はパラメータを必要としません。
</Callout>

<table>
  <thead>
    <tr>
      <th width="25%">
        パラメーター
      </th>

      <th>
        説明
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `エラー`

        _タプル_
      </td>

      <td>
        オプションで、ほとんど使われません。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info) から返される例外情報（exception_class, exception_instance, traceback）を含むタプルです。
      </td>
    </tr>

    <tr>
      <td>
        `属性`

        _ディクト_
      </td>

      <td>
        オプションです。エラーイベントに追加するカスタム属性（トランザクションに既に追加されているカスタム属性に加えて）。 [ハイセキュリティモード](/docs/agents/manage-apm-agents/configuration/high-security-mode) が有効になっている場合、これは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `予想`

        _boolean, iterable\[String], callable(exception_class, exception_instance, traceback)->boolean_
      </td>

      <td>
        オプションです。予想されるものとしてマークするエラーは、 `module:class` という形式の文字列のイテレート可能なものとして渡すことができます。この値は callable や、エラーが予想されるかどうかを示す Boolean にすることもできます。これらのエラーはUIに報告されますが、Apdexのスコアやエラー率には影響しません。
      </td>
    </tr>

    <tr>
      <td>
        `ignore`

        _boolean, iterable\[String], callable(exception_class, exception_instance, traceback)->boolean_
      </td>

      <td>
        オプションです。無視するエラーは、 `module:class` のような形式の文字列のイテレート可能な値として渡すことができます。この値は callable や、エラーを無視するかどうかを示す Boolean にすることもできます。ある種の例外が常に無視され、記録されない場合に便利です。
      </td>
    </tr>

    <tr>
      <td>
        `ステータスコード`

        _文字列、整数、callable(exception_class, exception_instance, traceback)_
      </td>

      <td>
        任意です。例外のステータスコードです。この値は、文字列、整数、または [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info) から返される例外情報 (exception_class, exception_instance, traceback) を取り込み、ステータスコードを整数で返す callable のいずれかです。
      </td>
    </tr>

    <tr>
      <td>
        `アプリケーション`

        _アプリケーションオブジェクト_
      </td>

      <td>
        オプションです。監視対象のウェブリクエストやバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`アプリケーション` オブジェクト](/docs/agents/python-agent/python-agent-api/application) が提供されない限り、呼び出しは無視されます。
      </td>
    </tr>
  </tbody>
</table>

## 戻り値

なし。

## 例

### 例外の報告の簡単な例 [#simple-example]

大半の場合、パラメータを渡す必要はありません。例外を報告したい場所で次のように呼べばよいのです。

```
newrelic.agent.notice_error()
```

### booleanを使った例 [#boolean-example]

`notice_error` の例では、ブール値を使用しています。これは、エラーが予想されることを示しています。

```
newrelic.agent.notice_error(expected=True)
```

### sys.exc_info()タプルと追加パラメータを用いたコール [#complex-example]

`notice_error` using `sys.exc_info()` data の例です。

```
def complex_ignore_errors(exc, val, tb):
   # do some logic here
   return False

newrelic.agent.notice_error(attributes={'my_special_exception': True}, ignore=complex_ignore_errors)
```

### コールバックの使用例 [#callback-example]

特定の例外タイプの属性に基づいて例外を動的にフィルタリングする必要がある場合は、コールバック関数を指定できます。

```
def _ignore_errors(exc, value, tb):
    if instance(value, HTTPError):
        if value.status == 404:
            return True

newrelic.agent.notice_error(ignore=_ignore_errors)
```

例外を無視/予期する場合は、 callable の戻り値を `True` に設定してください。他のチェックに関係なく、例外を決して無視/予期してはならない場合は `False` を、後続のチェックや内蔵のルールによって例外を無視/予期すべきかどうかを決定すべき場合は `None` を返します。コールバックは通常、 `True` または `None` のいずれかを返します。
